/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeCellularAutomata */

#ifndef _Included_NativeCellularAutomata
#define _Included_NativeCellularAutomata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeCellularAutomata
 * Method:    setup
 * Signature: (IIIIIII[D)Z
 */
JNIEXPORT jboolean JNICALL Java_NativeCellularAutomata_setup
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     NativeCellularAutomata
 * Method:    initCondition
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_NativeCellularAutomata_initCondition
  (JNIEnv *, jobject);

/*
 * Class:     NativeCellularAutomata
 * Method:    update
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_NativeCellularAutomata_update
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeCellularAutomata
 * Method:    finalCondition
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_NativeCellularAutomata_finalCondition
  (JNIEnv *, jobject);

/*
 * Class:     NativeCellularAutomata
 * Method:    getBuffer
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_NativeCellularAutomata_getBuffer
  (JNIEnv *, jobject);

/*
 * Class:     NativeCellularAutomata
 * Method:    getErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeCellularAutomata_getErrorMessage
  (JNIEnv *, jobject);

/*
 * Class:     NativeCellularAutomata
 * Method:    getModelDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeCellularAutomata_getModelDescription
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
